# Generated by Django 5.1.2 on 2024-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_staff_age_alter_staff_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(verbose_name='Joining Date'),
        ),
    ]
