# Generated by Django 5.1.2 on 2024-11-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_staff_gender_alter_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender'), (4, 'Gender Neutral')], default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default=False, max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Canceled', 'Canceled')], default=False, max_length=20, verbose_name='Status'),
        ),
    ]
