# Generated by Django 5.1.2 on 2024-11-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_admin_alter_staff_gender_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, verbose_name='Order ID')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('is_paid', models.BooleanField(verbose_name='Payment Status')),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled'), (5, 'Returned')], default=False, verbose_name='Order Status')),
                ('responsible_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.staff', verbose_name='Responsible Staff Member')),
            ],
        ),
    ]
