# Generated by Django 5.1.2 on 2024-11-10 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_staff_is_registered_alter_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_registered',
            field=models.BooleanField(choices=[(True, 'Registered'), (False, 'Unregistered')], default=None, verbose_name='Registration Status'),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(verbose_name='Assigned Date')),
                ('completion_deadline', models.DateField(verbose_name='Completion Deadline')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.task')),
            ],
        ),
    ]
